INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Aruba',NULL,NULL),
	 ('Afganistán',NULL,NULL),
	 ('Angola',NULL,NULL),
	 ('Anguila',NULL,NULL),
	 ('Islas de Åland',NULL,NULL),
	 ('Albania',NULL,NULL),
	 ('Andorra',NULL,NULL),
	 ('Emiratos Árabes Unidos',NULL,NULL),
	 ('Argentina',NULL,NULL),
	 ('Armenia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Samoa Americana',NULL,NULL),
	 ('Antarctica',NULL,NULL),
	 ('Territorios Australes y Antárticas Franceses',NULL,NULL),
	 ('Antigua and Barbuda',NULL,NULL),
	 ('Australia',NULL,NULL),
	 ('Austria',NULL,NULL),
	 ('Azerbayán',NULL,NULL),
	 ('Burundi',NULL,NULL),
	 ('Bélgica',NULL,NULL),
	 ('Benín',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Bonaire, San Eustaquio y Saba',NULL,NULL),
	 ('Burkina Faso',NULL,NULL),
	 ('Bangladesh',NULL,NULL),
	 ('Bulgaria',NULL,NULL),
	 ('Bahrein',NULL,NULL),
	 ('Bahamas',NULL,NULL),
	 ('Bosnia and Herzegovina',NULL,NULL),
	 ('San Bartolomé',NULL,NULL),
	 ('Bielorrusia',NULL,NULL),
	 ('Belice',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Islas Bermudas',NULL,NULL),
	 ('Bolivia',NULL,NULL),
	 ('Brasil',NULL,NULL),
	 ('Barbados',NULL,NULL),
	 ('Brunéi',NULL,NULL),
	 ('Bhután',NULL,NULL),
	 ('Isla Bouvet',NULL,NULL),
	 ('Botsuana',NULL,NULL),
	 ('República Centroafricana',NULL,NULL),
	 ('Canada',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Islas Cocos (Keeling)',NULL,NULL),
	 ('Suiza',NULL,NULL),
	 ('Chile',NULL,NULL),
	 ('China',NULL,NULL),
	 ('Costa de Marfil',NULL,NULL),
	 ('Camerún',NULL,NULL),
	 ('Congo, República Democrática del',NULL,NULL),
	 ('Congo',NULL,NULL),
	 ('Islas Cook',NULL,NULL),
	 ('Colombia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Comoras',NULL,NULL),
	 ('Cabo Verde',NULL,NULL),
	 ('Costa Rica',NULL,NULL),
	 ('Cuba',NULL,NULL),
	 ('Curazao',NULL,NULL),
	 ('Isla de Navidad',NULL,NULL),
	 ('Islas Caimán',NULL,NULL),
	 ('Chipre',NULL,NULL),
	 ('República Checa',NULL,NULL),
	 ('Alemania',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Yibuti',NULL,NULL),
	 ('Dominica',NULL,NULL),
	 ('Dinamarca',NULL,NULL),
	 ('República Dominicana',NULL,NULL),
	 ('Argelia',NULL,NULL),
	 ('Ecuador',NULL,NULL),
	 ('Egipto',NULL,NULL),
	 ('Eritrea',NULL,NULL),
	 ('Sahara Occidental',NULL,NULL),
	 ('España',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Estonia',NULL,NULL),
	 ('Etiopía',NULL,NULL),
	 ('Finlandia',NULL,NULL),
	 ('Fiji',NULL,NULL),
	 ('Islas Malvinas',NULL,NULL),
	 ('Francia',NULL,NULL),
	 ('Islas Feroe',NULL,NULL),
	 ('Micronesia',NULL,NULL),
	 ('Gabon',NULL,NULL),
	 ('Reino Unido',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Georgia',NULL,NULL),
	 ('Guernsey',NULL,NULL),
	 ('Ghana',NULL,NULL),
	 ('Gibraltar',NULL,NULL),
	 ('Guinea',NULL,NULL),
	 ('Guadalupe',NULL,NULL),
	 ('Gambia',NULL,NULL),
	 ('Guinea-Bissau',NULL,NULL),
	 ('Guinea Ecuatorial',NULL,NULL),
	 ('Grecia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Granada',NULL,NULL),
	 ('Groenlandia',NULL,NULL),
	 ('Guatemala',NULL,NULL),
	 ('Guayana Francesa',NULL,NULL),
	 ('Guam',NULL,NULL),
	 ('Guyana',NULL,NULL),
	 ('Hong Kong',NULL,NULL),
	 ('Islas Heard y McDonald',NULL,NULL),
	 ('Honduras',NULL,NULL),
	 ('Croacia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Haití',NULL,NULL),
	 ('Hungría',NULL,NULL),
	 ('Indonesia',NULL,NULL),
	 ('Isla de Man',NULL,NULL),
	 ('India',NULL,NULL),
	 ('Territorio Británico del Océano Índico',NULL,NULL),
	 ('Irlanda',NULL,NULL),
	 ('Irán',NULL,NULL),
	 ('Irak',NULL,NULL),
	 ('Islandia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Israel',NULL,NULL),
	 ('Italia',NULL,NULL),
	 ('Jamaica',NULL,NULL),
	 ('Jersey',NULL,NULL),
	 ('Jordania',NULL,NULL),
	 ('Japón',NULL,NULL),
	 ('Kazajistán',NULL,NULL),
	 ('Kenia',NULL,NULL),
	 ('Kirgizstán',NULL,NULL),
	 ('Camboya',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Kiribati',NULL,NULL),
	 ('Saint Kitts and Nevis',NULL,NULL),
	 ('Corea del Sur',NULL,NULL),
	 ('Kuwait',NULL,NULL),
	 ('Laos',NULL,NULL),
	 ('Lebanon',NULL,NULL),
	 ('Liberia',NULL,NULL),
	 ('Libia',NULL,NULL),
	 ('Santa Lucía',NULL,NULL),
	 ('Liechtenstein',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Sri Lanka',NULL,NULL),
	 ('Lesoto',NULL,NULL),
	 ('Lituania',NULL,NULL),
	 ('Luxemburgo',NULL,NULL),
	 ('Letonia',NULL,NULL),
	 ('Macao',NULL,NULL),
	 ('San Martín (Francia)',NULL,NULL),
	 ('Marruecos',NULL,NULL),
	 ('Monaco',NULL,NULL),
	 ('Moldavia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Madagascar',NULL,NULL),
	 ('Islas Maldivas',NULL,NULL),
	 ('Mexico',NULL,NULL),
	 ('Islas Marshall',NULL,NULL),
	 ('Macedônia',NULL,NULL),
	 ('Mali',NULL,NULL),
	 ('Malta',NULL,NULL),
	 ('Birmania',NULL,NULL),
	 ('Montenegro',NULL,NULL),
	 ('Mongolia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Islas Marianas del Norte',NULL,NULL),
	 ('Mozambique',NULL,NULL),
	 ('Mauritania',NULL,NULL),
	 ('Montserrat',NULL,NULL),
	 ('Martinica',NULL,NULL),
	 ('Mauricio',NULL,NULL),
	 ('Malawi',NULL,NULL),
	 ('Malasia',NULL,NULL),
	 ('Mayotte',NULL,NULL),
	 ('Namibia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Nueva Caledonia',NULL,NULL),
	 ('Niger',NULL,NULL),
	 ('Norfolk Island',NULL,NULL),
	 ('Nigeria',NULL,NULL),
	 ('Nicaragua',NULL,NULL),
	 ('Niue',NULL,NULL),
	 ('Países Bajos',NULL,NULL),
	 ('Norway',NULL,NULL),
	 ('Nepal',NULL,NULL),
	 ('Nauru',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Nueva Zelanda',NULL,NULL),
	 ('Omán',NULL,NULL),
	 ('Pakistán',NULL,NULL),
	 ('Panamá',NULL,NULL),
	 ('Pitcairn',NULL,NULL),
	 ('Perú',NULL,NULL),
	 ('Filipinas',NULL,NULL),
	 ('Palau',NULL,NULL),
	 ('Papúa Nueva Guinea',NULL,NULL),
	 ('Polonia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Puerto Rico',NULL,NULL),
	 ('Corea del Norte',NULL,NULL),
	 ('Portugal',NULL,NULL),
	 ('Paraguay',NULL,NULL),
	 ('Palestina',NULL,NULL),
	 ('Polinesia Francesa',NULL,NULL),
	 ('Qatar',NULL,NULL),
	 ('Reunión',NULL,NULL),
	 ('Rumanía',NULL,NULL),
	 ('Rusia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Ruanda',NULL,NULL),
	 ('Arabia Saudita',NULL,NULL),
	 ('Sudán',NULL,NULL),
	 ('Senegal',NULL,NULL),
	 ('Singapur',NULL,NULL),
	 ('Islas Georgias del Sur y Sandwich del Sur',NULL,NULL),
	 ('Santa Elena',NULL,NULL),
	 ('Svalbard y Jan Mayen',NULL,NULL),
	 ('Solomon Islands',NULL,NULL),
	 ('Sierra Leona',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('El Salvador',NULL,NULL),
	 ('San Marino',NULL,NULL),
	 ('Somalia',NULL,NULL),
	 ('San Pedro y Miquelón',NULL,NULL),
	 ('Serbia',NULL,NULL),
	 ('Sudán del Sur',NULL,NULL),
	 ('Santo Tomé y Príncipe',NULL,NULL),
	 ('Surinám',NULL,NULL),
	 ('Eslovaquia',NULL,NULL),
	 ('Eslovenia',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Suecia',NULL,NULL),
	 ('Swazilandia',NULL,NULL),
	 ('Sint Maarten',NULL,NULL),
	 ('Seychelles',NULL,NULL),
	 ('Siria',NULL,NULL),
	 ('Islas Turcas y Caicos',NULL,NULL),
	 ('Chad',NULL,NULL),
	 ('Togo',NULL,NULL),
	 ('Tailandia',NULL,NULL),
	 ('Tadjikistán',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Tokelau',NULL,NULL),
	 ('Turkmenistan',NULL,NULL),
	 ('Timor Oriental',NULL,NULL),
	 ('Tonga',NULL,NULL),
	 ('Trinidad y Tobago',NULL,NULL),
	 ('Tunez',NULL,NULL),
	 ('Turquía',NULL,NULL),
	 ('Tuvalu',NULL,NULL),
	 ('Taiwán',NULL,NULL),
	 ('Tanzania',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Uganda',NULL,NULL),
	 ('Ucrania',NULL,NULL),
	 ('Islas Ultramarinas Menores de Estados Unidos',NULL,NULL),
	 ('Uruguay',NULL,NULL),
	 ('Estados Unidos de América',NULL,NULL),
	 ('Uzbekistán',NULL,NULL),
	 ('Ciudad del Vaticano',NULL,NULL),
	 ('San Vicente y las Granadinas',NULL,NULL),
	 ('Venezuela',NULL,NULL),
	 ('Islas Vírgenes Británicas',NULL,NULL);
INSERT INTO dnf.country (name,created_at,updated_at) VALUES
	 ('Islas Vírgenes de los Estados Unidos',NULL,NULL),
	 ('Vietnam',NULL,NULL),
	 ('Vanuatu',NULL,NULL),
	 ('Wallis y Futuna',NULL,NULL),
	 ('Samoa',NULL,NULL),
	 ('Yemen',NULL,NULL),
	 ('Sudáfrica',NULL,NULL),
	 ('Zambia',NULL,NULL),
	 ('Zimbabwe',NULL,NULL);